---
- name: Filebeat playbook
  hosts: webservers
  become: true
  tasks:

  - name: Download and Install Filebeat
    apt:
      deb: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb"

  - name: Copy Filebeat config file
    copy:
      src: /etc/ansible/filebeat/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and Configure System Module
    command: "filebeat modules enable system"

  - name: Filebeat setup
    command: "filebeat setup"

  - name: Start filebeat
    command: "systemctl start filebeat"

  - name: Enable Filebeat on boot
    command: "systemctl enable filebeat"
