---
- name: Metric playbook
  hosts: webservers
  become: true
  tasks:

  - name: Download and Install Metricbeat
    apt:
      deb: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb"

  - name: Copy Metricbeat config file
    copy:
      src: /etc/ansible/metricbeat/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable Docker
    command: "metricbeat modules enable docker"

  - name: Metricbeat setup
    command: "metricbeat setup"

  - name: Start Metricbeat
    command: "systemctl start metricbeat"

#  - name: Some Metricbeat command
 #   command: "metricbeat -e"

  - name: Enable Metricbeat on boot
    command: "systemctl enable metricbeat"
